
name: CI

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Java JDK
      uses: actions/setup-java@v3
      with:
       distribution: 'adopt'
       java-version: '15'
    - name: Build the windows project
      run: ./gradlew packageReleaseExe
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: exe artifact
        path: build/compose/binaries/main-release/app/*.exe
